const std = @import("std");

pub const Edge = enum(u32) {
    left = 0,
    right = 1,
    top = 2,
    bottom = 3,
};

pub const TaskWindow = struct {
    hwnd: *anyopaque,
    title: [*:0]const u8,
    icon: ?*anyopaque,
    exe_path: [*:0]const u8,
};

pub const Action = enum {
    none,
    quit,
    focus_left,
    focus_right,
    move_left,
    move_right,
    increase_width,
    decrease_width,
    toggle_fullscreen,
    workspace_up,
    workspace_down,
    move_workspace_up,
    move_workspace_down,
    switch_workspace_1,
    switch_workspace_2,
    switch_workspace_3,
    switch_workspace_4,
    switch_workspace_5,
    switch_workspace_6,
    switch_workspace_7,
    switch_workspace_8,
    switch_workspace_9,
    move_to_workspace_1,
    move_to_workspace_2,
    move_to_workspace_3,
    move_to_workspace_4,
    move_to_workspace_5,
    move_to_workspace_6,
    move_to_workspace_7,
    move_to_workspace_8,
    move_to_workspace_9,
    focus_column_1,
    focus_column_2,
    focus_column_3,
    focus_column_4,
    focus_column_5,
    focus_column_6,
    focus_column_7,
    focus_column_8,
    focus_column_9,
    close_window,
};